# Note that the following stanza uses CircleCI 2.1 to make use of a Reusable Executor
# This allows defining a docker image to reuse across jobs.
# visit https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors to learn more.

version: 2.1

executors:
  test-loader:
    docker:
      - image: alpine:latest
    working_directory: /tmp
  my-executor:
    docker:
      - image: desmonddak/python_light:latest
    working_directory: /tmp
  other-executor:
    docker:
      - image: desmonddak/new-git:latest
    working_directory: /tmp

jobs:
  load:
    executor: test-loader
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: cp -a tests workspace
      
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - tests

  flow:
    executor: my-executor
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run: echo "Hello, world!" > workspace/echo-output
      
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output

  downstream:
    executor: other-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            ls /tmp/workspace/tests/
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2.1

  btd:
    jobs:
      - load
      - flow:
          requires:
            - load
      - downstream:
          requires:
            - flow
